cabal-version: 2.2


name:           kiwi
version:        0.1.2.0
description:    Please see the README on GitHub at <https://github.com/PaulRivier/kiwi>
homepage:       https://github.com/PaulRivier/kiwi
bug-reports:    https://github.com/PaulRivier/kiwi
author:         Paul Rivier
maintainer:     Paul Rivier
copyright:      2020 Paul Rivier
license:        BSD-3-Clause
license-file:   LICENSE
build-type:     Simple
extra-source-files:
    README.md
    ChangeLog.md

source-repository head
  type: git
  location: https://github.com/PaulRivier/kiwi



common ghc-opts
  ghc-options: -Wall -threaded 

common deps
  build-depends:
      aeson
    , async
    , base >=4.7 && <5
    , base16-bytestring
    , blaze-builder
    , blaze-html
    , blaze-markup
    , bytestring
    , commonmark
    , commonmark-extensions    
    , commonmark-pandoc
    , config-ini
    , containers
    , cookie
    , cryptohash
    , directory
    , filepath
    , full-text-search
    , hashable
    , http-types
    , mtl
    , optparse-applicative
    -- , pandoc
    , pandoc-types
    , process
    , random
    , raw-strings-qq
    , scotty
    , snowball
    , stache
    , text
    , text-icu
    , time
    , unliftio-core 
    , utf8-string
    , wai
    , wai-extra
    , wai-middleware-static

-- Shared language edition
common lang
  default-language: Haskell2010

  
library
  import:  ghc-opts, deps, lang
  exposed-modules:
      Kiwi
      Kiwi.CLI
      Kiwi.ConfigFile
      Kiwi.Controller
      Kiwi.DefaultPages
      Kiwi.Locales
      Kiwi.HtmlWriter
      Kiwi.PagesDB
      Kiwi.Pandoc
      Kiwi.Search
      Kiwi.Server
      Kiwi.Types
      Kiwi.Utils
      Kiwi.View
      Utils.Cookies
      Utils.DocIndex
  other-modules: Paths_kiwi
  hs-source-dirs: src

executable kiwi
  import:  ghc-opts, deps, lang
  build-depends: kiwi
  main-is: Main.hs
  other-modules: Paths_kiwi
  hs-source-dirs: app
  ghc-options: -rtsopts -with-rtsopts=-N


test-suite kiwi-test
  import:  ghc-opts, deps, lang
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  other-modules: Paths_kiwi
  hs-source-dirs: test
