name:                kiwi
version:             0.1.0.0
github:              "githubuser/kiwi"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/kiwi#readme>

dependencies:
- aeson
- async
- base >= 4.7 && < 5
- base16-bytestring
- blaze-builder
- bytestring
- cookie
- config-ini
- containers
- cryptohash
- directory
- filepath
- full-text-search
- hashable
- http-types
# - lucid
- optparse-applicative
- mtl
- pandoc
- pandoc-types
# - parsec
- process
- scotty
- text
- time
- random
- raw-strings-qq
- snowball
- stache
- text-icu
- utf8-string
- wai
- wai-extra
- wai-middleware-static

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  kiwi:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kiwi

tests:
  kiwi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kiwi
